workflows:
  android-build:
    name: Android Build
    environment:
      groups:
        - android_config
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
